### ISSUE TITLE
Why the double useMemo?

### ISSUE THREAD

**Issue by wmertens** [alex-cory/use-ssr#16]
I don't understand this code: https://github.com/alex-cory/use-ssr/blob/88e408cffbcff17a0bad63d1c86b9f00d110862c/useSSR.ts#L51

```js

  const useSSRObject = useMemo(() => ({
    isBrowser: whereAmI === BROWSER,
    isServer: whereAmI === SERVER,
    isNative: whereAmI === NATIVE,
    canUseWorkers: typeof Worker !== 'undefined',
    canUseEventListeners: whereAmI === BROWSER && !!window.addEventListener,
    canUseViewport: whereAmI === BROWSER && !!window.screen
  }), [whereAmI])

  return useMemo(() => Object.assign(Object.values(useSSRObject), useSSRObject), [whereAmI])
```

First it creates `useSSRObject`, which seems like it should be sufficient, and then it creates an array of the values that also looks like `useSSRObject`?

Also, all these values are static, so they could just be exported from a module without all the hooks?

**Comment by wmertens** [comment]
ah ok, the array+object is to allow both `[isBrowser, isServer, ...]` and direct property access. Still, that could be done in the first useMemo, no?

Another observation: how about just exporting the static values, and a function that you can call on the server to set `isServer:true`? That way, there's no guesswork and no hooks needed?

**Comment by iamthesiz** [comment]
When would we need to explicitly set `isServer` to true?

**Comment by iamthesiz** [comment]
Honestly, it's probably an overuse of `useMemo`.

**Comment by wmertens** [comment]
Ah, I didn't get around to commenting yet - actually for hydration it should be possible to turn on `isServer` and then turn it off. Coincidentally, there's a discussion at https://github.com/GoogleChromeLabs/react-adaptive-hooks/issues/18 on how to do this best.
